language: node_js
sudo: false
node_js:
- '0.10'
- '0.11'

cache:
 directories:
  - node_modules
  - bower_components


install:
 - npm install
 - npm install jshint
 - bower install

addons:
  sauce_connect: true

notifications:
 email:
 - mirco.bellagamba@outlook.it
