language: node_js
sudo: false
node_js:
- '0.12'
cache:
 directories:
  - node_modules
  - bower_components

env:
  global:
    - secure: OxUym4hBXsICycM4GsDenYvtOu0C44V67I4N+vzqI7xsXfX4ek4TKHlQRRD4M3gxzSf0D+Nz+YgrX6/Z0UiPf8H8uz9BxoXxyTZVbKPh+bhFfHL56Btt5BfRVPw0IBgVzWRoeEQZyDRM2EwL3l5Og1bVDE7KOA7aeDmOS9o4eZOaGs0JfYCyib3niWBfyk+5eynu4xfQYGnDTFpdbj6viU6+wn8eUyX7W2N8B22+buWJLOipJKMCbdfbq30vwEk1sXQYKdpMCSw8xOYHFjtBr4LQCWheiXt1sEzmX+i9W2417dVokF0ODY6PBwMX044MW8eOOHXe1K4sjT8ECATpkpDDVwYzw8hAa4uTD/n3IgviEBZU1xuN/zNwZVI6VwTsyfalS78zvqmBEVbc1tl/kRRlTPeaLL9MJeLTt05PmZhvbaJVUIScjfJi03+qzWrxq66a3TClQ+xYgCRqc/zC0jsENEArWTS0NgAodA98AXf4G3kAtwrV85E2NeYqa60LwQfikgyOFW7vQV/8wCtKtqs8BbM1pgRWJWOtYjSXNzVh97nV9e/qXK/sDt2+M6N32HAphHxDcBOqZm3+RoWaJ8fnkxsd5DgY4zYydkNEBAVvB+ufY0SXALTjLg2ha+UAQCZwGnLM4BhztFbmW9DbSUbk2hUFqpEYBurk7bNfEa4=
    - secure: WQ7UnPQjSzk3+ZZcysYpp/diK8bih1MlPOOrljXmRfR/oHYYi+/yvcM/Gu3o89ATGSNIQUmTpTrcdCTCJD01cdywKxOoxlX5laUtWz4XA/fmtsz29+ploHJzFtfALep0leFrISsx5Wrx9OEoO0u2S5QWw+Z5UTFmalqiaTPo/E4Dr842c3cj9ogDYF6ain39kSyHuPSuG+iKX+6DGIPv74Iy68ZdUgeJgYbzn2FY1iZ6g6gtjjS6x1IhIQMHxH1+X7qBrddV4r3kkImcQS77u1PdsFq3+SqtR+omhz7UrFHcWmE0Nxw+pM66HmJIhP45rEub2liC/QKMNI1LQkegEZkdM43ooPsrr7W9vH5qk374KXLTSHzi2ch4OIf2SHgWPMSu9RGWCu/8fSRBWjZiqMupQkZBTTQyU/MZugQPwrD/pFkIHSMLK5x2eYn/Kx/EQ9W9MdHn62aRrmsWFrAo2J42pIYwA+KTjIT23DgnPKxST50m2v2j9oiyBubvqm6FvyN1PC+DQB7GZTKKoMylprFzX5Qah9ImXrkYBwLMH91LmrT3kNAyd6mE0Aw8JS4HBSE348QThwbcS+Zwk5lLWcliabW5zaLMEuq3JlZ8Wg/xq+VObBXVl655Qjx2E6j04wtgF+pQmXSOTpbAKRlmkh39gWte5U51MiykaDAHXVY=

install:
 - npm install
 - bower install

before_script: npm install -g karma-cli

script:
 - karma start test/karma.conf-ci.js

addons:
  sauce_connect: true

notifications:
 email:
 - mirco.bellagamba@outlook.it
